# Use the official NGINX image from the Docker Hub
FROM nginx:alpine

# Copy the HTML file to the NGINX default HTML directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to the outside world
EXPOSE 80

